// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	"errors"
	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// DatabaseRoleList is a list of DatabaseRole
type DatabaseRoleList struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringOutput `pulumi:"apiVersion"`
	// List of databaseroles. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items DatabaseRoleTypeArrayOutput `pulumi:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata metav1.ListMetaOutput `pulumi:"metadata"`
}

// NewDatabaseRoleList registers a new resource with the given unique name, arguments, and options.
func NewDatabaseRoleList(ctx *pulumi.Context,
	name string, args *DatabaseRoleListArgs, opts ...pulumi.ResourceOption) (*DatabaseRoleList, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Items == nil {
		return nil, errors.New("invalid value for required argument 'Items'")
	}
	args.ApiVersion = pulumi.StringPtr("postgresql.cnpg.io/v1")
	args.Kind = pulumi.StringPtr("DatabaseRoleList")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource DatabaseRoleList
	err := ctx.RegisterResource("kubernetes:postgresql.cnpg.io/v1:DatabaseRoleList", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDatabaseRoleList gets an existing DatabaseRoleList resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDatabaseRoleList(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DatabaseRoleListState, opts ...pulumi.ResourceOption) (*DatabaseRoleList, error) {
	var resource DatabaseRoleList
	err := ctx.ReadResource("kubernetes:postgresql.cnpg.io/v1:DatabaseRoleList", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DatabaseRoleList resources.
type databaseRoleListState struct {
}

type DatabaseRoleListState struct {
}

func (DatabaseRoleListState) ElementType() reflect.Type {
	return reflect.TypeOf((*databaseRoleListState)(nil)).Elem()
}

type databaseRoleListArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// List of databaseroles. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items []DatabaseRoleType `pulumi:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `pulumi:"metadata"`
}

// The set of arguments for constructing a DatabaseRoleList resource.
type DatabaseRoleListArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// List of databaseroles. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items DatabaseRoleTypeArrayInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata metav1.ListMetaPtrInput
}

func (DatabaseRoleListArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*databaseRoleListArgs)(nil)).Elem()
}

type DatabaseRoleListInput interface {
	pulumi.Input

	ToDatabaseRoleListOutput() DatabaseRoleListOutput
	ToDatabaseRoleListOutputWithContext(ctx context.Context) DatabaseRoleListOutput
}

func (*DatabaseRoleList) ElementType() reflect.Type {
	return reflect.TypeOf((**DatabaseRoleList)(nil)).Elem()
}

func (i *DatabaseRoleList) ToDatabaseRoleListOutput() DatabaseRoleListOutput {
	return i.ToDatabaseRoleListOutputWithContext(context.Background())
}

func (i *DatabaseRoleList) ToDatabaseRoleListOutputWithContext(ctx context.Context) DatabaseRoleListOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatabaseRoleListOutput)
}

// DatabaseRoleListArrayInput is an input type that accepts DatabaseRoleListArray and DatabaseRoleListArrayOutput values.
// You can construct a concrete instance of `DatabaseRoleListArrayInput` via:
//
//	DatabaseRoleListArray{ DatabaseRoleListArgs{...} }
type DatabaseRoleListArrayInput interface {
	pulumi.Input

	ToDatabaseRoleListArrayOutput() DatabaseRoleListArrayOutput
	ToDatabaseRoleListArrayOutputWithContext(context.Context) DatabaseRoleListArrayOutput
}

type DatabaseRoleListArray []DatabaseRoleListInput

func (DatabaseRoleListArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DatabaseRoleList)(nil)).Elem()
}

func (i DatabaseRoleListArray) ToDatabaseRoleListArrayOutput() DatabaseRoleListArrayOutput {
	return i.ToDatabaseRoleListArrayOutputWithContext(context.Background())
}

func (i DatabaseRoleListArray) ToDatabaseRoleListArrayOutputWithContext(ctx context.Context) DatabaseRoleListArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatabaseRoleListArrayOutput)
}

// DatabaseRoleListMapInput is an input type that accepts DatabaseRoleListMap and DatabaseRoleListMapOutput values.
// You can construct a concrete instance of `DatabaseRoleListMapInput` via:
//
//	DatabaseRoleListMap{ "key": DatabaseRoleListArgs{...} }
type DatabaseRoleListMapInput interface {
	pulumi.Input

	ToDatabaseRoleListMapOutput() DatabaseRoleListMapOutput
	ToDatabaseRoleListMapOutputWithContext(context.Context) DatabaseRoleListMapOutput
}

type DatabaseRoleListMap map[string]DatabaseRoleListInput

func (DatabaseRoleListMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DatabaseRoleList)(nil)).Elem()
}

func (i DatabaseRoleListMap) ToDatabaseRoleListMapOutput() DatabaseRoleListMapOutput {
	return i.ToDatabaseRoleListMapOutputWithContext(context.Background())
}

func (i DatabaseRoleListMap) ToDatabaseRoleListMapOutputWithContext(ctx context.Context) DatabaseRoleListMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatabaseRoleListMapOutput)
}

type DatabaseRoleListOutput struct{ *pulumi.OutputState }

func (DatabaseRoleListOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DatabaseRoleList)(nil)).Elem()
}

func (o DatabaseRoleListOutput) ToDatabaseRoleListOutput() DatabaseRoleListOutput {
	return o
}

func (o DatabaseRoleListOutput) ToDatabaseRoleListOutputWithContext(ctx context.Context) DatabaseRoleListOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o DatabaseRoleListOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *DatabaseRoleList) pulumi.StringOutput { return v.ApiVersion }).(pulumi.StringOutput)
}

// List of databaseroles. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
func (o DatabaseRoleListOutput) Items() DatabaseRoleTypeArrayOutput {
	return o.ApplyT(func(v *DatabaseRoleList) DatabaseRoleTypeArrayOutput { return v.Items }).(DatabaseRoleTypeArrayOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o DatabaseRoleListOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *DatabaseRoleList) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o DatabaseRoleListOutput) Metadata() metav1.ListMetaOutput {
	return o.ApplyT(func(v *DatabaseRoleList) metav1.ListMetaOutput { return v.Metadata }).(metav1.ListMetaOutput)
}

type DatabaseRoleListArrayOutput struct{ *pulumi.OutputState }

func (DatabaseRoleListArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DatabaseRoleList)(nil)).Elem()
}

func (o DatabaseRoleListArrayOutput) ToDatabaseRoleListArrayOutput() DatabaseRoleListArrayOutput {
	return o
}

func (o DatabaseRoleListArrayOutput) ToDatabaseRoleListArrayOutputWithContext(ctx context.Context) DatabaseRoleListArrayOutput {
	return o
}

func (o DatabaseRoleListArrayOutput) Index(i pulumi.IntInput) DatabaseRoleListOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DatabaseRoleList {
		return vs[0].([]*DatabaseRoleList)[vs[1].(int)]
	}).(DatabaseRoleListOutput)
}

type DatabaseRoleListMapOutput struct{ *pulumi.OutputState }

func (DatabaseRoleListMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DatabaseRoleList)(nil)).Elem()
}

func (o DatabaseRoleListMapOutput) ToDatabaseRoleListMapOutput() DatabaseRoleListMapOutput {
	return o
}

func (o DatabaseRoleListMapOutput) ToDatabaseRoleListMapOutputWithContext(ctx context.Context) DatabaseRoleListMapOutput {
	return o
}

func (o DatabaseRoleListMapOutput) MapIndex(k pulumi.StringInput) DatabaseRoleListOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DatabaseRoleList {
		return vs[0].(map[string]*DatabaseRoleList)[vs[1].(string)]
	}).(DatabaseRoleListOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DatabaseRoleListInput)(nil)).Elem(), &DatabaseRoleList{})
	pulumi.RegisterInputType(reflect.TypeOf((*DatabaseRoleListArrayInput)(nil)).Elem(), DatabaseRoleListArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DatabaseRoleListMapInput)(nil)).Elem(), DatabaseRoleListMap{})
	pulumi.RegisterOutputType(DatabaseRoleListOutput{})
	pulumi.RegisterOutputType(DatabaseRoleListArrayOutput{})
	pulumi.RegisterOutputType(DatabaseRoleListMapOutput{})
}
