// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Patch resources are used to modify existing Kubernetes resources by using
// Server-Side Apply updates. The name of the resource must be specified, but all other properties are optional. More than
// one patch may be applied to the same resource, and a random FieldManager name will be used for each Patch resource.
// Conflicts will result in an error by default, but can be forced using the "pulumi.com/patchForce" annotation. See the
// [Server-Side Apply Docs](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/) for
// additional information about using Server-Side Apply to manage Kubernetes resources with Pulumi.
// DatabaseRole is the Schema for the databaseroles API
type DatabaseRolePatch struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrOutput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrOutput `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPatchPtrOutput  `pulumi:"metadata"`
	Spec     DatabaseRoleSpecPatchPtrOutput   `pulumi:"spec"`
	Status   DatabaseRoleStatusPatchPtrOutput `pulumi:"status"`
}

// NewDatabaseRolePatch registers a new resource with the given unique name, arguments, and options.
func NewDatabaseRolePatch(ctx *pulumi.Context,
	name string, args *DatabaseRolePatchArgs, opts ...pulumi.ResourceOption) (*DatabaseRolePatch, error) {
	if args == nil {
		args = &DatabaseRolePatchArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("postgresql.cnpg.io/v1")
	args.Kind = pulumi.StringPtr("DatabaseRole")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource DatabaseRolePatch
	err := ctx.RegisterResource("kubernetes:postgresql.cnpg.io/v1:DatabaseRolePatch", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDatabaseRolePatch gets an existing DatabaseRolePatch resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDatabaseRolePatch(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DatabaseRolePatchState, opts ...pulumi.ResourceOption) (*DatabaseRolePatch, error) {
	var resource DatabaseRolePatch
	err := ctx.ReadResource("kubernetes:postgresql.cnpg.io/v1:DatabaseRolePatch", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DatabaseRolePatch resources.
type databaseRolePatchState struct {
}

type DatabaseRolePatchState struct {
}

func (DatabaseRolePatchState) ElementType() reflect.Type {
	return reflect.TypeOf((*databaseRolePatchState)(nil)).Elem()
}

type databaseRolePatchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMetaPatch `pulumi:"metadata"`
	Spec     *DatabaseRoleSpecPatch  `pulumi:"spec"`
}

// The set of arguments for constructing a DatabaseRolePatch resource.
type DatabaseRolePatchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPatchPtrInput
	Spec     DatabaseRoleSpecPatchPtrInput
}

func (DatabaseRolePatchArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*databaseRolePatchArgs)(nil)).Elem()
}

type DatabaseRolePatchInput interface {
	pulumi.Input

	ToDatabaseRolePatchOutput() DatabaseRolePatchOutput
	ToDatabaseRolePatchOutputWithContext(ctx context.Context) DatabaseRolePatchOutput
}

func (*DatabaseRolePatch) ElementType() reflect.Type {
	return reflect.TypeOf((**DatabaseRolePatch)(nil)).Elem()
}

func (i *DatabaseRolePatch) ToDatabaseRolePatchOutput() DatabaseRolePatchOutput {
	return i.ToDatabaseRolePatchOutputWithContext(context.Background())
}

func (i *DatabaseRolePatch) ToDatabaseRolePatchOutputWithContext(ctx context.Context) DatabaseRolePatchOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatabaseRolePatchOutput)
}

// DatabaseRolePatchArrayInput is an input type that accepts DatabaseRolePatchArray and DatabaseRolePatchArrayOutput values.
// You can construct a concrete instance of `DatabaseRolePatchArrayInput` via:
//
//	DatabaseRolePatchArray{ DatabaseRolePatchArgs{...} }
type DatabaseRolePatchArrayInput interface {
	pulumi.Input

	ToDatabaseRolePatchArrayOutput() DatabaseRolePatchArrayOutput
	ToDatabaseRolePatchArrayOutputWithContext(context.Context) DatabaseRolePatchArrayOutput
}

type DatabaseRolePatchArray []DatabaseRolePatchInput

func (DatabaseRolePatchArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DatabaseRolePatch)(nil)).Elem()
}

func (i DatabaseRolePatchArray) ToDatabaseRolePatchArrayOutput() DatabaseRolePatchArrayOutput {
	return i.ToDatabaseRolePatchArrayOutputWithContext(context.Background())
}

func (i DatabaseRolePatchArray) ToDatabaseRolePatchArrayOutputWithContext(ctx context.Context) DatabaseRolePatchArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatabaseRolePatchArrayOutput)
}

// DatabaseRolePatchMapInput is an input type that accepts DatabaseRolePatchMap and DatabaseRolePatchMapOutput values.
// You can construct a concrete instance of `DatabaseRolePatchMapInput` via:
//
//	DatabaseRolePatchMap{ "key": DatabaseRolePatchArgs{...} }
type DatabaseRolePatchMapInput interface {
	pulumi.Input

	ToDatabaseRolePatchMapOutput() DatabaseRolePatchMapOutput
	ToDatabaseRolePatchMapOutputWithContext(context.Context) DatabaseRolePatchMapOutput
}

type DatabaseRolePatchMap map[string]DatabaseRolePatchInput

func (DatabaseRolePatchMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DatabaseRolePatch)(nil)).Elem()
}

func (i DatabaseRolePatchMap) ToDatabaseRolePatchMapOutput() DatabaseRolePatchMapOutput {
	return i.ToDatabaseRolePatchMapOutputWithContext(context.Background())
}

func (i DatabaseRolePatchMap) ToDatabaseRolePatchMapOutputWithContext(ctx context.Context) DatabaseRolePatchMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatabaseRolePatchMapOutput)
}

type DatabaseRolePatchOutput struct{ *pulumi.OutputState }

func (DatabaseRolePatchOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DatabaseRolePatch)(nil)).Elem()
}

func (o DatabaseRolePatchOutput) ToDatabaseRolePatchOutput() DatabaseRolePatchOutput {
	return o
}

func (o DatabaseRolePatchOutput) ToDatabaseRolePatchOutputWithContext(ctx context.Context) DatabaseRolePatchOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o DatabaseRolePatchOutput) ApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DatabaseRolePatch) pulumi.StringPtrOutput { return v.ApiVersion }).(pulumi.StringPtrOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o DatabaseRolePatchOutput) Kind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DatabaseRolePatch) pulumi.StringPtrOutput { return v.Kind }).(pulumi.StringPtrOutput)
}

// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o DatabaseRolePatchOutput) Metadata() metav1.ObjectMetaPatchPtrOutput {
	return o.ApplyT(func(v *DatabaseRolePatch) metav1.ObjectMetaPatchPtrOutput { return v.Metadata }).(metav1.ObjectMetaPatchPtrOutput)
}

func (o DatabaseRolePatchOutput) Spec() DatabaseRoleSpecPatchPtrOutput {
	return o.ApplyT(func(v *DatabaseRolePatch) DatabaseRoleSpecPatchPtrOutput { return v.Spec }).(DatabaseRoleSpecPatchPtrOutput)
}

func (o DatabaseRolePatchOutput) Status() DatabaseRoleStatusPatchPtrOutput {
	return o.ApplyT(func(v *DatabaseRolePatch) DatabaseRoleStatusPatchPtrOutput { return v.Status }).(DatabaseRoleStatusPatchPtrOutput)
}

type DatabaseRolePatchArrayOutput struct{ *pulumi.OutputState }

func (DatabaseRolePatchArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DatabaseRolePatch)(nil)).Elem()
}

func (o DatabaseRolePatchArrayOutput) ToDatabaseRolePatchArrayOutput() DatabaseRolePatchArrayOutput {
	return o
}

func (o DatabaseRolePatchArrayOutput) ToDatabaseRolePatchArrayOutputWithContext(ctx context.Context) DatabaseRolePatchArrayOutput {
	return o
}

func (o DatabaseRolePatchArrayOutput) Index(i pulumi.IntInput) DatabaseRolePatchOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DatabaseRolePatch {
		return vs[0].([]*DatabaseRolePatch)[vs[1].(int)]
	}).(DatabaseRolePatchOutput)
}

type DatabaseRolePatchMapOutput struct{ *pulumi.OutputState }

func (DatabaseRolePatchMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DatabaseRolePatch)(nil)).Elem()
}

func (o DatabaseRolePatchMapOutput) ToDatabaseRolePatchMapOutput() DatabaseRolePatchMapOutput {
	return o
}

func (o DatabaseRolePatchMapOutput) ToDatabaseRolePatchMapOutputWithContext(ctx context.Context) DatabaseRolePatchMapOutput {
	return o
}

func (o DatabaseRolePatchMapOutput) MapIndex(k pulumi.StringInput) DatabaseRolePatchOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DatabaseRolePatch {
		return vs[0].(map[string]*DatabaseRolePatch)[vs[1].(string)]
	}).(DatabaseRolePatchOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DatabaseRolePatchInput)(nil)).Elem(), &DatabaseRolePatch{})
	pulumi.RegisterInputType(reflect.TypeOf((*DatabaseRolePatchArrayInput)(nil)).Elem(), DatabaseRolePatchArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DatabaseRolePatchMapInput)(nil)).Elem(), DatabaseRolePatchMap{})
	pulumi.RegisterOutputType(DatabaseRolePatchOutput{})
	pulumi.RegisterOutputType(DatabaseRolePatchArrayOutput{})
	pulumi.RegisterOutputType(DatabaseRolePatchMapOutput{})
}
