// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// FailoverQuorum contains the information about the current failover
// quorum status of a PG cluster. It is updated by the instance manager
// of the primary node and reset to zero by the operator to trigger
// an update.
type FailoverQuorum struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringOutput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaOutput       `pulumi:"metadata"`
	Status   FailoverQuorumStatusPtrOutput `pulumi:"status"`
}

// NewFailoverQuorum registers a new resource with the given unique name, arguments, and options.
func NewFailoverQuorum(ctx *pulumi.Context,
	name string, args *FailoverQuorumArgs, opts ...pulumi.ResourceOption) (*FailoverQuorum, error) {
	if args == nil {
		args = &FailoverQuorumArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("postgresql.cnpg.io/v1")
	args.Kind = pulumi.StringPtr("FailoverQuorum")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource FailoverQuorum
	err := ctx.RegisterResource("kubernetes:postgresql.cnpg.io/v1:FailoverQuorum", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFailoverQuorum gets an existing FailoverQuorum resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFailoverQuorum(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FailoverQuorumState, opts ...pulumi.ResourceOption) (*FailoverQuorum, error) {
	var resource FailoverQuorum
	err := ctx.ReadResource("kubernetes:postgresql.cnpg.io/v1:FailoverQuorum", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering FailoverQuorum resources.
type failoverQuorumState struct {
}

type FailoverQuorumState struct {
}

func (FailoverQuorumState) ElementType() reflect.Type {
	return reflect.TypeOf((*failoverQuorumState)(nil)).Elem()
}

type failoverQuorumArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `pulumi:"metadata"`
}

// The set of arguments for constructing a FailoverQuorum resource.
type FailoverQuorumArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPtrInput
}

func (FailoverQuorumArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*failoverQuorumArgs)(nil)).Elem()
}

type FailoverQuorumInput interface {
	pulumi.Input

	ToFailoverQuorumOutput() FailoverQuorumOutput
	ToFailoverQuorumOutputWithContext(ctx context.Context) FailoverQuorumOutput
}

func (*FailoverQuorum) ElementType() reflect.Type {
	return reflect.TypeOf((**FailoverQuorum)(nil)).Elem()
}

func (i *FailoverQuorum) ToFailoverQuorumOutput() FailoverQuorumOutput {
	return i.ToFailoverQuorumOutputWithContext(context.Background())
}

func (i *FailoverQuorum) ToFailoverQuorumOutputWithContext(ctx context.Context) FailoverQuorumOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FailoverQuorumOutput)
}

// FailoverQuorumArrayInput is an input type that accepts FailoverQuorumArray and FailoverQuorumArrayOutput values.
// You can construct a concrete instance of `FailoverQuorumArrayInput` via:
//
//	FailoverQuorumArray{ FailoverQuorumArgs{...} }
type FailoverQuorumArrayInput interface {
	pulumi.Input

	ToFailoverQuorumArrayOutput() FailoverQuorumArrayOutput
	ToFailoverQuorumArrayOutputWithContext(context.Context) FailoverQuorumArrayOutput
}

type FailoverQuorumArray []FailoverQuorumInput

func (FailoverQuorumArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FailoverQuorum)(nil)).Elem()
}

func (i FailoverQuorumArray) ToFailoverQuorumArrayOutput() FailoverQuorumArrayOutput {
	return i.ToFailoverQuorumArrayOutputWithContext(context.Background())
}

func (i FailoverQuorumArray) ToFailoverQuorumArrayOutputWithContext(ctx context.Context) FailoverQuorumArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FailoverQuorumArrayOutput)
}

// FailoverQuorumMapInput is an input type that accepts FailoverQuorumMap and FailoverQuorumMapOutput values.
// You can construct a concrete instance of `FailoverQuorumMapInput` via:
//
//	FailoverQuorumMap{ "key": FailoverQuorumArgs{...} }
type FailoverQuorumMapInput interface {
	pulumi.Input

	ToFailoverQuorumMapOutput() FailoverQuorumMapOutput
	ToFailoverQuorumMapOutputWithContext(context.Context) FailoverQuorumMapOutput
}

type FailoverQuorumMap map[string]FailoverQuorumInput

func (FailoverQuorumMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FailoverQuorum)(nil)).Elem()
}

func (i FailoverQuorumMap) ToFailoverQuorumMapOutput() FailoverQuorumMapOutput {
	return i.ToFailoverQuorumMapOutputWithContext(context.Background())
}

func (i FailoverQuorumMap) ToFailoverQuorumMapOutputWithContext(ctx context.Context) FailoverQuorumMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FailoverQuorumMapOutput)
}

type FailoverQuorumOutput struct{ *pulumi.OutputState }

func (FailoverQuorumOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FailoverQuorum)(nil)).Elem()
}

func (o FailoverQuorumOutput) ToFailoverQuorumOutput() FailoverQuorumOutput {
	return o
}

func (o FailoverQuorumOutput) ToFailoverQuorumOutputWithContext(ctx context.Context) FailoverQuorumOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o FailoverQuorumOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *FailoverQuorum) pulumi.StringOutput { return v.ApiVersion }).(pulumi.StringOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o FailoverQuorumOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *FailoverQuorum) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o FailoverQuorumOutput) Metadata() metav1.ObjectMetaOutput {
	return o.ApplyT(func(v *FailoverQuorum) metav1.ObjectMetaOutput { return v.Metadata }).(metav1.ObjectMetaOutput)
}

func (o FailoverQuorumOutput) Status() FailoverQuorumStatusPtrOutput {
	return o.ApplyT(func(v *FailoverQuorum) FailoverQuorumStatusPtrOutput { return v.Status }).(FailoverQuorumStatusPtrOutput)
}

type FailoverQuorumArrayOutput struct{ *pulumi.OutputState }

func (FailoverQuorumArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FailoverQuorum)(nil)).Elem()
}

func (o FailoverQuorumArrayOutput) ToFailoverQuorumArrayOutput() FailoverQuorumArrayOutput {
	return o
}

func (o FailoverQuorumArrayOutput) ToFailoverQuorumArrayOutputWithContext(ctx context.Context) FailoverQuorumArrayOutput {
	return o
}

func (o FailoverQuorumArrayOutput) Index(i pulumi.IntInput) FailoverQuorumOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *FailoverQuorum {
		return vs[0].([]*FailoverQuorum)[vs[1].(int)]
	}).(FailoverQuorumOutput)
}

type FailoverQuorumMapOutput struct{ *pulumi.OutputState }

func (FailoverQuorumMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FailoverQuorum)(nil)).Elem()
}

func (o FailoverQuorumMapOutput) ToFailoverQuorumMapOutput() FailoverQuorumMapOutput {
	return o
}

func (o FailoverQuorumMapOutput) ToFailoverQuorumMapOutputWithContext(ctx context.Context) FailoverQuorumMapOutput {
	return o
}

func (o FailoverQuorumMapOutput) MapIndex(k pulumi.StringInput) FailoverQuorumOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *FailoverQuorum {
		return vs[0].(map[string]*FailoverQuorum)[vs[1].(string)]
	}).(FailoverQuorumOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FailoverQuorumInput)(nil)).Elem(), &FailoverQuorum{})
	pulumi.RegisterInputType(reflect.TypeOf((*FailoverQuorumArrayInput)(nil)).Elem(), FailoverQuorumArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*FailoverQuorumMapInput)(nil)).Elem(), FailoverQuorumMap{})
	pulumi.RegisterOutputType(FailoverQuorumOutput{})
	pulumi.RegisterOutputType(FailoverQuorumArrayOutput{})
	pulumi.RegisterOutputType(FailoverQuorumMapOutput{})
}
