// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Patch resources are used to modify existing Kubernetes resources by using
// Server-Side Apply updates. The name of the resource must be specified, but all other properties are optional. More than
// one patch may be applied to the same resource, and a random FieldManager name will be used for each Patch resource.
// Conflicts will result in an error by default, but can be forced using the "pulumi.com/patchForce" annotation. See the
// [Server-Side Apply Docs](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/) for
// additional information about using Server-Side Apply to manage Kubernetes resources with Pulumi.
// FailoverQuorum contains the information about the current failover
// quorum status of a PG cluster. It is updated by the instance manager
// of the primary node and reset to zero by the operator to trigger
// an update.
type FailoverQuorumPatch struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrOutput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrOutput `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPatchPtrOutput    `pulumi:"metadata"`
	Status   FailoverQuorumStatusPatchPtrOutput `pulumi:"status"`
}

// NewFailoverQuorumPatch registers a new resource with the given unique name, arguments, and options.
func NewFailoverQuorumPatch(ctx *pulumi.Context,
	name string, args *FailoverQuorumPatchArgs, opts ...pulumi.ResourceOption) (*FailoverQuorumPatch, error) {
	if args == nil {
		args = &FailoverQuorumPatchArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("postgresql.cnpg.io/v1")
	args.Kind = pulumi.StringPtr("FailoverQuorum")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource FailoverQuorumPatch
	err := ctx.RegisterResource("kubernetes:postgresql.cnpg.io/v1:FailoverQuorumPatch", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFailoverQuorumPatch gets an existing FailoverQuorumPatch resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFailoverQuorumPatch(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FailoverQuorumPatchState, opts ...pulumi.ResourceOption) (*FailoverQuorumPatch, error) {
	var resource FailoverQuorumPatch
	err := ctx.ReadResource("kubernetes:postgresql.cnpg.io/v1:FailoverQuorumPatch", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering FailoverQuorumPatch resources.
type failoverQuorumPatchState struct {
}

type FailoverQuorumPatchState struct {
}

func (FailoverQuorumPatchState) ElementType() reflect.Type {
	return reflect.TypeOf((*failoverQuorumPatchState)(nil)).Elem()
}

type failoverQuorumPatchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMetaPatch `pulumi:"metadata"`
}

// The set of arguments for constructing a FailoverQuorumPatch resource.
type FailoverQuorumPatchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPatchPtrInput
}

func (FailoverQuorumPatchArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*failoverQuorumPatchArgs)(nil)).Elem()
}

type FailoverQuorumPatchInput interface {
	pulumi.Input

	ToFailoverQuorumPatchOutput() FailoverQuorumPatchOutput
	ToFailoverQuorumPatchOutputWithContext(ctx context.Context) FailoverQuorumPatchOutput
}

func (*FailoverQuorumPatch) ElementType() reflect.Type {
	return reflect.TypeOf((**FailoverQuorumPatch)(nil)).Elem()
}

func (i *FailoverQuorumPatch) ToFailoverQuorumPatchOutput() FailoverQuorumPatchOutput {
	return i.ToFailoverQuorumPatchOutputWithContext(context.Background())
}

func (i *FailoverQuorumPatch) ToFailoverQuorumPatchOutputWithContext(ctx context.Context) FailoverQuorumPatchOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FailoverQuorumPatchOutput)
}

// FailoverQuorumPatchArrayInput is an input type that accepts FailoverQuorumPatchArray and FailoverQuorumPatchArrayOutput values.
// You can construct a concrete instance of `FailoverQuorumPatchArrayInput` via:
//
//	FailoverQuorumPatchArray{ FailoverQuorumPatchArgs{...} }
type FailoverQuorumPatchArrayInput interface {
	pulumi.Input

	ToFailoverQuorumPatchArrayOutput() FailoverQuorumPatchArrayOutput
	ToFailoverQuorumPatchArrayOutputWithContext(context.Context) FailoverQuorumPatchArrayOutput
}

type FailoverQuorumPatchArray []FailoverQuorumPatchInput

func (FailoverQuorumPatchArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FailoverQuorumPatch)(nil)).Elem()
}

func (i FailoverQuorumPatchArray) ToFailoverQuorumPatchArrayOutput() FailoverQuorumPatchArrayOutput {
	return i.ToFailoverQuorumPatchArrayOutputWithContext(context.Background())
}

func (i FailoverQuorumPatchArray) ToFailoverQuorumPatchArrayOutputWithContext(ctx context.Context) FailoverQuorumPatchArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FailoverQuorumPatchArrayOutput)
}

// FailoverQuorumPatchMapInput is an input type that accepts FailoverQuorumPatchMap and FailoverQuorumPatchMapOutput values.
// You can construct a concrete instance of `FailoverQuorumPatchMapInput` via:
//
//	FailoverQuorumPatchMap{ "key": FailoverQuorumPatchArgs{...} }
type FailoverQuorumPatchMapInput interface {
	pulumi.Input

	ToFailoverQuorumPatchMapOutput() FailoverQuorumPatchMapOutput
	ToFailoverQuorumPatchMapOutputWithContext(context.Context) FailoverQuorumPatchMapOutput
}

type FailoverQuorumPatchMap map[string]FailoverQuorumPatchInput

func (FailoverQuorumPatchMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FailoverQuorumPatch)(nil)).Elem()
}

func (i FailoverQuorumPatchMap) ToFailoverQuorumPatchMapOutput() FailoverQuorumPatchMapOutput {
	return i.ToFailoverQuorumPatchMapOutputWithContext(context.Background())
}

func (i FailoverQuorumPatchMap) ToFailoverQuorumPatchMapOutputWithContext(ctx context.Context) FailoverQuorumPatchMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FailoverQuorumPatchMapOutput)
}

type FailoverQuorumPatchOutput struct{ *pulumi.OutputState }

func (FailoverQuorumPatchOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FailoverQuorumPatch)(nil)).Elem()
}

func (o FailoverQuorumPatchOutput) ToFailoverQuorumPatchOutput() FailoverQuorumPatchOutput {
	return o
}

func (o FailoverQuorumPatchOutput) ToFailoverQuorumPatchOutputWithContext(ctx context.Context) FailoverQuorumPatchOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o FailoverQuorumPatchOutput) ApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *FailoverQuorumPatch) pulumi.StringPtrOutput { return v.ApiVersion }).(pulumi.StringPtrOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o FailoverQuorumPatchOutput) Kind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *FailoverQuorumPatch) pulumi.StringPtrOutput { return v.Kind }).(pulumi.StringPtrOutput)
}

// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o FailoverQuorumPatchOutput) Metadata() metav1.ObjectMetaPatchPtrOutput {
	return o.ApplyT(func(v *FailoverQuorumPatch) metav1.ObjectMetaPatchPtrOutput { return v.Metadata }).(metav1.ObjectMetaPatchPtrOutput)
}

func (o FailoverQuorumPatchOutput) Status() FailoverQuorumStatusPatchPtrOutput {
	return o.ApplyT(func(v *FailoverQuorumPatch) FailoverQuorumStatusPatchPtrOutput { return v.Status }).(FailoverQuorumStatusPatchPtrOutput)
}

type FailoverQuorumPatchArrayOutput struct{ *pulumi.OutputState }

func (FailoverQuorumPatchArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FailoverQuorumPatch)(nil)).Elem()
}

func (o FailoverQuorumPatchArrayOutput) ToFailoverQuorumPatchArrayOutput() FailoverQuorumPatchArrayOutput {
	return o
}

func (o FailoverQuorumPatchArrayOutput) ToFailoverQuorumPatchArrayOutputWithContext(ctx context.Context) FailoverQuorumPatchArrayOutput {
	return o
}

func (o FailoverQuorumPatchArrayOutput) Index(i pulumi.IntInput) FailoverQuorumPatchOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *FailoverQuorumPatch {
		return vs[0].([]*FailoverQuorumPatch)[vs[1].(int)]
	}).(FailoverQuorumPatchOutput)
}

type FailoverQuorumPatchMapOutput struct{ *pulumi.OutputState }

func (FailoverQuorumPatchMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FailoverQuorumPatch)(nil)).Elem()
}

func (o FailoverQuorumPatchMapOutput) ToFailoverQuorumPatchMapOutput() FailoverQuorumPatchMapOutput {
	return o
}

func (o FailoverQuorumPatchMapOutput) ToFailoverQuorumPatchMapOutputWithContext(ctx context.Context) FailoverQuorumPatchMapOutput {
	return o
}

func (o FailoverQuorumPatchMapOutput) MapIndex(k pulumi.StringInput) FailoverQuorumPatchOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *FailoverQuorumPatch {
		return vs[0].(map[string]*FailoverQuorumPatch)[vs[1].(string)]
	}).(FailoverQuorumPatchOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FailoverQuorumPatchInput)(nil)).Elem(), &FailoverQuorumPatch{})
	pulumi.RegisterInputType(reflect.TypeOf((*FailoverQuorumPatchArrayInput)(nil)).Elem(), FailoverQuorumPatchArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*FailoverQuorumPatchMapInput)(nil)).Elem(), FailoverQuorumPatchMap{})
	pulumi.RegisterOutputType(FailoverQuorumPatchOutput{})
	pulumi.RegisterOutputType(FailoverQuorumPatchArrayOutput{})
	pulumi.RegisterOutputType(FailoverQuorumPatchMapOutput{})
}
