// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	"errors"
	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// FailoverQuorumList is a list of FailoverQuorum
type FailoverQuorumList struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringOutput `pulumi:"apiVersion"`
	// List of failoverquorums. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items FailoverQuorumTypeArrayOutput `pulumi:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata metav1.ListMetaOutput `pulumi:"metadata"`
}

// NewFailoverQuorumList registers a new resource with the given unique name, arguments, and options.
func NewFailoverQuorumList(ctx *pulumi.Context,
	name string, args *FailoverQuorumListArgs, opts ...pulumi.ResourceOption) (*FailoverQuorumList, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Items == nil {
		return nil, errors.New("invalid value for required argument 'Items'")
	}
	args.ApiVersion = pulumi.StringPtr("postgresql.cnpg.io/v1")
	args.Kind = pulumi.StringPtr("FailoverQuorumList")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource FailoverQuorumList
	err := ctx.RegisterResource("kubernetes:postgresql.cnpg.io/v1:FailoverQuorumList", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFailoverQuorumList gets an existing FailoverQuorumList resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFailoverQuorumList(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FailoverQuorumListState, opts ...pulumi.ResourceOption) (*FailoverQuorumList, error) {
	var resource FailoverQuorumList
	err := ctx.ReadResource("kubernetes:postgresql.cnpg.io/v1:FailoverQuorumList", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering FailoverQuorumList resources.
type failoverQuorumListState struct {
}

type FailoverQuorumListState struct {
}

func (FailoverQuorumListState) ElementType() reflect.Type {
	return reflect.TypeOf((*failoverQuorumListState)(nil)).Elem()
}

type failoverQuorumListArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// List of failoverquorums. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items []FailoverQuorumType `pulumi:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `pulumi:"metadata"`
}

// The set of arguments for constructing a FailoverQuorumList resource.
type FailoverQuorumListArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// List of failoverquorums. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items FailoverQuorumTypeArrayInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata metav1.ListMetaPtrInput
}

func (FailoverQuorumListArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*failoverQuorumListArgs)(nil)).Elem()
}

type FailoverQuorumListInput interface {
	pulumi.Input

	ToFailoverQuorumListOutput() FailoverQuorumListOutput
	ToFailoverQuorumListOutputWithContext(ctx context.Context) FailoverQuorumListOutput
}

func (*FailoverQuorumList) ElementType() reflect.Type {
	return reflect.TypeOf((**FailoverQuorumList)(nil)).Elem()
}

func (i *FailoverQuorumList) ToFailoverQuorumListOutput() FailoverQuorumListOutput {
	return i.ToFailoverQuorumListOutputWithContext(context.Background())
}

func (i *FailoverQuorumList) ToFailoverQuorumListOutputWithContext(ctx context.Context) FailoverQuorumListOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FailoverQuorumListOutput)
}

// FailoverQuorumListArrayInput is an input type that accepts FailoverQuorumListArray and FailoverQuorumListArrayOutput values.
// You can construct a concrete instance of `FailoverQuorumListArrayInput` via:
//
//	FailoverQuorumListArray{ FailoverQuorumListArgs{...} }
type FailoverQuorumListArrayInput interface {
	pulumi.Input

	ToFailoverQuorumListArrayOutput() FailoverQuorumListArrayOutput
	ToFailoverQuorumListArrayOutputWithContext(context.Context) FailoverQuorumListArrayOutput
}

type FailoverQuorumListArray []FailoverQuorumListInput

func (FailoverQuorumListArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FailoverQuorumList)(nil)).Elem()
}

func (i FailoverQuorumListArray) ToFailoverQuorumListArrayOutput() FailoverQuorumListArrayOutput {
	return i.ToFailoverQuorumListArrayOutputWithContext(context.Background())
}

func (i FailoverQuorumListArray) ToFailoverQuorumListArrayOutputWithContext(ctx context.Context) FailoverQuorumListArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FailoverQuorumListArrayOutput)
}

// FailoverQuorumListMapInput is an input type that accepts FailoverQuorumListMap and FailoverQuorumListMapOutput values.
// You can construct a concrete instance of `FailoverQuorumListMapInput` via:
//
//	FailoverQuorumListMap{ "key": FailoverQuorumListArgs{...} }
type FailoverQuorumListMapInput interface {
	pulumi.Input

	ToFailoverQuorumListMapOutput() FailoverQuorumListMapOutput
	ToFailoverQuorumListMapOutputWithContext(context.Context) FailoverQuorumListMapOutput
}

type FailoverQuorumListMap map[string]FailoverQuorumListInput

func (FailoverQuorumListMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FailoverQuorumList)(nil)).Elem()
}

func (i FailoverQuorumListMap) ToFailoverQuorumListMapOutput() FailoverQuorumListMapOutput {
	return i.ToFailoverQuorumListMapOutputWithContext(context.Background())
}

func (i FailoverQuorumListMap) ToFailoverQuorumListMapOutputWithContext(ctx context.Context) FailoverQuorumListMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FailoverQuorumListMapOutput)
}

type FailoverQuorumListOutput struct{ *pulumi.OutputState }

func (FailoverQuorumListOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FailoverQuorumList)(nil)).Elem()
}

func (o FailoverQuorumListOutput) ToFailoverQuorumListOutput() FailoverQuorumListOutput {
	return o
}

func (o FailoverQuorumListOutput) ToFailoverQuorumListOutputWithContext(ctx context.Context) FailoverQuorumListOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o FailoverQuorumListOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *FailoverQuorumList) pulumi.StringOutput { return v.ApiVersion }).(pulumi.StringOutput)
}

// List of failoverquorums. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
func (o FailoverQuorumListOutput) Items() FailoverQuorumTypeArrayOutput {
	return o.ApplyT(func(v *FailoverQuorumList) FailoverQuorumTypeArrayOutput { return v.Items }).(FailoverQuorumTypeArrayOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o FailoverQuorumListOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *FailoverQuorumList) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o FailoverQuorumListOutput) Metadata() metav1.ListMetaOutput {
	return o.ApplyT(func(v *FailoverQuorumList) metav1.ListMetaOutput { return v.Metadata }).(metav1.ListMetaOutput)
}

type FailoverQuorumListArrayOutput struct{ *pulumi.OutputState }

func (FailoverQuorumListArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FailoverQuorumList)(nil)).Elem()
}

func (o FailoverQuorumListArrayOutput) ToFailoverQuorumListArrayOutput() FailoverQuorumListArrayOutput {
	return o
}

func (o FailoverQuorumListArrayOutput) ToFailoverQuorumListArrayOutputWithContext(ctx context.Context) FailoverQuorumListArrayOutput {
	return o
}

func (o FailoverQuorumListArrayOutput) Index(i pulumi.IntInput) FailoverQuorumListOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *FailoverQuorumList {
		return vs[0].([]*FailoverQuorumList)[vs[1].(int)]
	}).(FailoverQuorumListOutput)
}

type FailoverQuorumListMapOutput struct{ *pulumi.OutputState }

func (FailoverQuorumListMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FailoverQuorumList)(nil)).Elem()
}

func (o FailoverQuorumListMapOutput) ToFailoverQuorumListMapOutput() FailoverQuorumListMapOutput {
	return o
}

func (o FailoverQuorumListMapOutput) ToFailoverQuorumListMapOutputWithContext(ctx context.Context) FailoverQuorumListMapOutput {
	return o
}

func (o FailoverQuorumListMapOutput) MapIndex(k pulumi.StringInput) FailoverQuorumListOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *FailoverQuorumList {
		return vs[0].(map[string]*FailoverQuorumList)[vs[1].(string)]
	}).(FailoverQuorumListOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FailoverQuorumListInput)(nil)).Elem(), &FailoverQuorumList{})
	pulumi.RegisterInputType(reflect.TypeOf((*FailoverQuorumListArrayInput)(nil)).Elem(), FailoverQuorumListArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*FailoverQuorumListMapInput)(nil)).Elem(), FailoverQuorumListMap{})
	pulumi.RegisterOutputType(FailoverQuorumListOutput{})
	pulumi.RegisterOutputType(FailoverQuorumListArrayOutput{})
	pulumi.RegisterOutputType(FailoverQuorumListMapOutput{})
}
