name: Build and Publish Docker Image (PR)

on:
  pull_request:
    paths:
      - 'cmd/backup/main.go'
      - 'internal/backup/arangodb.go'
      - 'internal/backup/redis.go'
      - 'build/package/Dockerfile'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Setup just
        uses: extractions/setup-just@v4
        with:
          just-version: '1.58.0'

      - name: Build and publish backup image
        env:
          JUST_UNSTABLE: 1
        run: |
          just build-publish-backup-image --ref ${{ github.event.pull_request.head.sha }} \
            --user ${{ secrets.DOCKERHUB_USER }} \
            --pass ${{ secrets.DOCKER_PASS }}
