name: Continuous integration
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: set up golang
        uses: actions/setup-go@v5
        with:
          go-version: '~1.21.6'
      - name: check out code
        uses: actions/checkout@v4
      - name: run linter
        uses: golangci/golangci-lint-action@v4
        with: 
          version: v1.55.2
      - name: unit test
        run: go test -covermode=atomic -coverprofile=profile.cov -v ./...
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./profile.cov
